# Generated by Django 5.2.12 on 2026-04-02 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_permission_user_is_company_admin_and_more'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentline',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentsession',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentsession',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentsession',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentsession',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockalertevent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='stockalertrule',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockalertrule',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='stockalertrule',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location_reference_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockadjustmentline',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_adjustment_lines', to='core.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentsession',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_adjustment_sessions', to='core.company'),
        ),
        migrations.AlterField(
            model_name='stockadjustmentsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_alert_events', to='core.company'),
        ),
        migrations.AlterField(
            model_name='stockalertevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='stockalertrule',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_alert_rules', to='core.company'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='stock_movements', to='core.company'),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['company', 'normalized_name'], name='brands_company_ccd9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='itemmodel',
            index=models.Index(fields=['company', 'normalized_model_name'], name='item_models_company_98fbdc_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustmentline',
            index=models.Index(fields=['adjustment_session'], name='stock_adjus_adjustm_e4a648_idx'),
        ),
        migrations.AddIndex(
            model_name='stockcategory',
            index=models.Index(fields=['company', 'name'], name='stock_item__company_c5fe15_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company', 'reference_type', 'reference_id'], name='stock_movem_company_01d35b_idx'),
        ),
        migrations.AddIndex(
            model_name='stockserialunit',
            index=models.Index(fields=['company', 'serial_number'], name='stock_seria_company_c652b1_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'normalized_name'], name='vendor_refe_company_ae97a7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'code'], name='vendor_refe_company_9e2e14_idx'),
        ),
    ]
