# Generated by Django 5.2.12 on 2026-04-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_remove_stockadjustmentline_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadjustmentsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Adjustment Session', 'verbose_name_plural': 'Adjustment Sessions'},
        ),
        migrations.AlterModelOptions(
            name='stockalertevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock Alert Event', 'verbose_name_plural': 'Stock Alert Events'},
        ),
    ]
